name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make all VERBOSE=2 RELEASE=1
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test
      run: make test VERBOSE=2 RELEASE=1
